name: project_hospital_management
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  table_calendar: ^3.1.3
  font_awesome_flutter: ^10.8.0
  lottie: ^3.2.0
  flutter:
    sdk: flutter
  dio: ^5.7.0
  shared_preferences: ^2.3.4
  provider: ^6.1.2
  rating_dialog: ^2.0.4
  cupertino_icons: ^1.0.8
  dio_cookie_manager: ^3.1.1
  cookie_jar: ^4.0.8
  intl: ^0.19.0
  sqflite: ^2.4.1
  sqflite_common_ffi: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
